name: Pull Request (component)
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: openshift4-service-mesh

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ matrix.command }}
        run: make -C component ${{ matrix.command }}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Compile component
        run: make -C component test -e instance=${{ matrix.instance }}
  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Golden diff
        run: make -C component golden-diff -e instance=${{ matrix.instance }}
