name: Pull Request (package)
on:
  pull_request:
    branches:
      - master

env:
  PACKAGE_NAME: openshift4-service-mesh

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_yaml
          - lint_commodore
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.command }}
        run: make -C package ${{ matrix.command }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.PACKAGE_NAME }}
      - name: Compile component
        run: make  -C package test -e instance=${{ matrix.instance }}
  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.PACKAGE_NAME }}
      - name: Golden diff
        run: make -C package golden-diff -e instance=${{ matrix.instance }}
