name: Pull Request (global lints)

on:
  pull_request:
    branches:
      - master
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Asciidoc linter
        run: make lint_adoc

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
